### ISSUE TITLE
Is this file path wrong in CMakeLists.txt?

### ISSUE THREAD

**Issue by hhtdgit** [masssssha/misis2024s-23-02-mehova-m-s#1]
In the CMakeLists.txt file, there seems to be an error in the set statement on line 11.

`set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO ${CMAKE_CURRENT_SOURCE_DIR}bin.relwithdbg)`

Should the correct assignment part be as shown below?

`${CMAKE_CURRENT_SOURCE_DIR}/bin.relwithdbg`

**Comment by dvpsun** [comment]
Yes.
